import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://ekimero.com',
  base: '/',
  integrations: [sitemap()],
  redirects: {
    '/stations/:name.html': '/stations/:name',
    '/lines/:name.html': '/lines/:name',
    '/melodies/:name.html': '/melodies/:name',
    '/companies/:name.html': '/companies/:name',
    '/unused/:name.html': '/unused/:name',
    '/station/:name.html': '/stations/:name',
    '/line/:name.html': '/lines/:name',
    '/melody/:name.html': '/melodies/:name',
    '/company/:name.html': '/companies/:name',
    '/未使用/:name.html': '/unused/:name',
    '/credits.html': '/credits',
    '/history.html': '/history',
    '/search.html': '/search',
    '/stations.html': '/stations',
    '/lines.html': '/lines',
    '/melodies.html': '/melodies',
    '/companies.html': '/companies',
    '/unused.html': '/unused',
    '/未使用.html': '/unused',
    '/jr-east/:name.html': '/lines/:name',
    '/tokyo-metro/:name.html': '/lines/:name',
    '/toei/:name.html': '/lines/:name',
    '/jr-east.html': '/companies/JR東日本',
    '/tokyo-metro.html': '/companies/東京メトロ',
    '/toei.html': '/companies/都営地下鉄',
  },
});
